### ISSUE TITLE
Font for theorems etc

### ISSUE THREAD

**Issue by akissinger** [Compositionality/latex-template#8]
Fonts for amsthm environments seem to be slight different, and smaller than the surrounding text. Was this on purpose?

![2019-05-07_15-16-11](https://user-images.githubusercontent.com/881183/57302273-17259b00-70db-11e9-83af-08675c2e6ac9.png)

I can see the rationale in wanting to make some kind of visual distinction for math environments, but to my eyes this looks really bad, this this was pasted from a different document in MS word. I think it would be better to make the overall line spacing (cf #9) a bit less and put more of a gap around the environments.

**Comment by mroman42** [comment]
I agree. Instead of the current version (f6ad33bb574ad57b3d9fa6d64ebd1836f793404d), I am finding a text much easy on the eyes under the version `compositionalityarticle 2018/07/11 v2.0` that comes included with the arXiv versions of the accepted papers. For instance, the style of the journal webpage feels more natural than that of the articles with this template.

Would it be possible to go back to a more standard look? Or at least avoid the clash of two different font styles? Or at least give the option to use the same font for text and theorems to the authors?

**Comment by n-otter** [comment]
v2 of  `compositionalityarticle.cls` is now on github, and it addresses the font discrepancy.
